/**
 * Les sources SECONDAIRES de l'export, et la règle qui les gouverne.
 *
 * POURQUOI UN FICHIER À PART
 * --------------------------
 * `airbnbExport.test.js` vérifie la lecture des annonces. Celui-ci vérifie ce
 * qui est venu ensuite : les avis, les séjours, les modèles de message écrits
 * par l'hôte, la traçabilité des champs et l'arbitrage des désaccords entre
 * fichiers.
 *
 * Ces sources sont les plus risquées de l'export : ce sont celles où il serait
 * facile de fabriquer une caractéristique qui n'existe pas. La plupart des
 * tests ci-dessous vérifient donc qu'une donnée N'EST PAS écrite — un champ
 * vide est le résultat attendu, pas un échec.
 */

const { parseExportDocuments } = require('../services/airbnbExport');

const SMALL_ID = '39244203';
const BIG_ID = '1684090983577235984';

function listingsDoc(listings) {
  return { name: 'listings.json', data: [{ listings }] };
}

function rawListing(overrides = {}) {
  return {
    id: Number(SMALL_ID),
    nickname: null,
    propertyType: 'House',
    bedrooms: 2,
    beds: 3,
    bathrooms: 1,
    personCapacity: 5,
    city: 'Parempuyre',
    country: 'FR',
    zipcode: '33290',
    street: '12 Rue des Ardillères',
    formattedAddress: '12 Rue des Ardillères, 33290 Parempuyre, France',
    amenities: ['wireless_internet', 'kitchen'],
    listingDescriptions: [{ name: 'Studio CHIC et cosy', description: 'Une description.' }],
    ...overrides,
  };
}

function reservationsDoc(rows) {
  return { name: 'reservations.json', data: [{ reservations: rows }] };
}

function quickRepliesDoc(templates) {
  return { name: 'host_quick_replies.json', data: [{ templates }] };
}

const FUTURE = new Date(Date.now() + 90 * 86400000).toISOString().slice(0, 10);
const PAST = '2019-05-01';

// ────────────────────────────────────────────────────────────────────────────
describe('reviews.json — note moyenne et nombre d\'avis', () => {
  const reviewsDoc = {
    name: 'reviews.json',
    data: [{
      reviewsReceived: [
        // Comptés : avis reçus par l'hôte sur un logement, réellement soumis.
        { review: { entityType: 'HOME', revieweeRole: 'HOST', hasSubmitted: true, isSystemAutoGenerated: false, entityId: SMALL_ID, rating: 5 } },
        { review: { entityType: 'HOME', revieweeRole: 'HOST', hasSubmitted: true, isSystemAutoGenerated: false, entityId: SMALL_ID, rating: 4 } },
        // Écartés, un par motif — chacun fausserait la note du logement.
        { review: { entityType: 'HOME', revieweeRole: 'GUEST', hasSubmitted: true, isSystemAutoGenerated: false, entityId: SMALL_ID, rating: 1 } },
        { review: { entityType: 'HOME', revieweeRole: 'HOST', hasSubmitted: false, isSystemAutoGenerated: false, entityId: SMALL_ID, rating: 1 } },
        { review: { entityType: 'HOME', revieweeRole: 'HOST', hasSubmitted: true, isSystemAutoGenerated: true, entityId: SMALL_ID, rating: 1 } },
        { review: { entityType: 'HOME', revieweeRole: 'HOST', hasSubmitted: true, isSystemAutoGenerated: false, entityId: SMALL_ID, rating: null } },
      ],
      // Les avis que l'hôte a LAISSÉS à ses voyageurs ne sont pas la note de
      // son logement.
      reviewsProvided: [
        { review: { entityType: 'HOME', revieweeRole: 'GUEST', hasSubmitted: true, isSystemAutoGenerated: false, entityId: SMALL_ID, rating: 1 } },
      ],
    }],
  };

  it('calcule la moyenne sur les seuls avis recevables', () => {
    const [listing] = parseExportDocuments([listingsDoc([rawListing()]), reviewsDoc]).listings;
    expect(listing.review_count).toBe(2);
    expect(listing.rating).toBe(4.5);
    expect(listing.found.reviews).toBe(true);
    expect(listing.import_sources.rating).toBe('reviews.json');
  });

  it('ne pose aucune note quand aucun avis n\'est recevable', () => {
    const empty = {
      name: 'reviews.json',
      data: [{ reviewsReceived: [
        { review: { entityType: 'HOME', revieweeRole: 'GUEST', hasSubmitted: true, entityId: SMALL_ID, rating: 5 } },
      ] }],
    };
    const [listing] = parseExportDocuments([listingsDoc([rawListing()]), empty]).listings;
    expect(listing.rating).toBeUndefined();
    expect(listing.review_count).toBeUndefined();
    expect(listing.found.reviews).toBe(false);
  });
});

// ────────────────────────────────────────────────────────────────────────────
describe('reservations.json — séjours à venir', () => {
  it('ne retient que les séjours à venir et calcule la date de départ', () => {
    const { listings } = parseExportDocuments([
      listingsDoc([rawListing()]),
      reservationsDoc([
        { confirmationCode: 'FUTUR1', hostingUrl: `https://www.airbnb.com/rooms/${SMALL_ID}`, startDate: FUTURE, nights: 3, status: 'accepted', numberOfGuests: 2 },
        { confirmationCode: 'PASSE1', hostingUrl: `https://www.airbnb.com/rooms/${SMALL_ID}`, startDate: PAST, nights: 2, status: 'accepted', numberOfGuests: 2 },
      ]),
    ]);

    expect(listings[0].reservations).toHaveLength(1);
    const [stay] = listings[0].reservations;
    expect(stay.confirmation_code).toBe('FUTUR1');
    expect(stay.check_in_date).toBe(FUTURE);

    // Départ = arrivée + nuits. C'est la définition d'une nuitée, pas une
    // estimation : la date de départ n'existe pas telle quelle dans l'export.
    const expected = new Date(`${FUTURE}T00:00:00Z`);
    expected.setUTCDate(expected.getUTCDate() + 3);
    expect(stay.check_out_date).toBe(expected.toISOString().slice(0, 10));
    expect(listings[0].found.reservations).toBe(true);
  });

  it('ne fait entrer aucune donnée du voyageur dans la fiche', () => {
    const { listings } = parseExportDocuments([
      listingsDoc([rawListing()]),
      reservationsDoc([{
        confirmationCode: 'FUTUR2', hostingUrl: `https://www.airbnb.com/rooms/${SMALL_ID}`,
        startDate: FUTURE, nights: 2, status: 'accepted', numberOfGuests: 2,
        message: 'Bonjour, je serai en retard',
        guestProfileUrl: 'https://www.airbnb.com/users/show/999',
        guestVatCountry: 'FR', hostCurrency: 'EUR', guestCheckinTimeFrom: 21,
      }]),
    ]);

    const serialized = JSON.stringify(listings[0]);
    expect(serialized).not.toContain('en retard');
    expect(serialized).not.toContain('users/show/999');
    // `guestCheckinTimeFrom` est l'heure annoncée par CE voyageur : elle ne
    // doit jamais devenir l'heure d'arrivée du logement.
    expect(listings[0].check_in_time).toBeUndefined();
  });

  it('écarte un statut inconnu plutôt que de le traduire au jugé', () => {
    const { listings } = parseExportDocuments([
      listingsDoc([rawListing()]),
      reservationsDoc([
        { confirmationCode: 'X1', hostingUrl: `https://www.airbnb.com/rooms/${SMALL_ID}`, startDate: FUTURE, nights: 1, status: 'wibble' },
      ]),
    ]);
    expect(listings[0].reservations).toEqual([]);
  });

  it('écarte un séjour sans code de confirmation, faute de clé stable', () => {
    const { listings } = parseExportDocuments([
      listingsDoc([rawListing()]),
      reservationsDoc([
        { hostingUrl: `https://www.airbnb.com/rooms/${SMALL_ID}`, startDate: FUTURE, nights: 1, status: 'accepted' },
      ]),
    ]);
    expect(listings[0].reservations).toEqual([]);
  });

  it('ne crée pas de logement à partir d\'un séjour orphelin', () => {
    const { listings } = parseExportDocuments([
      listingsDoc([rawListing()]),
      reservationsDoc([
        { confirmationCode: 'ORPH', hostingUrl: 'https://www.airbnb.com/rooms/99998888', startDate: FUTURE, nights: 1, status: 'accepted' },
      ]),
    ]);
    expect(listings).toHaveLength(1);
    expect(listings[0].external_listing_id).toBe(SMALL_ID);
  });
});

// ────────────────────────────────────────────────────────────────────────────
describe('host_quick_replies.json — source secondaire sous conditions', () => {
  it('lit l\'heure d\'arrivée d\'un modèle qui ne vise QU\'UN logement', () => {
    const [listing] = parseExportDocuments([
      listingsDoc([rawListing()]),
      quickRepliesDoc([{
        entities: [{ entityType: 'LISTING', entityId: SMALL_ID }],
        texts: [{ message: 'Votre arrivée est possible à partir de 16h.', locale: 'fr' }],
      }]),
    ]).listings;

    expect(listing.check_in_time).toBe('16:00');
    // La provenance doit dire que cette valeur ne vient PAS de l'annonce.
    expect(listing.import_sources.check_in_time).toBe('host_quick_replies.json');
  });

  it('ignore un modèle rattaché à plusieurs logements', () => {
    const [listing] = parseExportDocuments([
      listingsDoc([rawListing()]),
      quickRepliesDoc([{
        entities: [
          { entityType: 'LISTING', entityId: SMALL_ID },
          { entityType: 'LISTING', entityId: BIG_ID },
        ],
        texts: [{ message: 'Arrivée à partir de 16h.', locale: 'fr' }],
      }]),
    ]).listings;
    expect(listing.check_in_time).toBeUndefined();
  });

  it('ignore un espace réservé : sa valeur n\'est pas dans l\'export', () => {
    const [listing] = parseExportDocuments([
      listingsDoc([rawListing()]),
      quickRepliesDoc([{
        entities: [{ entityType: 'LISTING', entityId: SMALL_ID }],
        texts: [{ message: 'Arrivée à partir de #{CHECK_IN_TIME}.', locale: 'fr' }],
      }]),
    ]).listings;
    expect(listing.check_in_time).toBeUndefined();
  });

  it('laisse le champ vide quand deux modèles se contredisent', () => {
    const [listing] = parseExportDocuments([
      listingsDoc([rawListing()]),
      quickRepliesDoc([
        { entities: [{ entityType: 'LISTING', entityId: SMALL_ID }], texts: [{ message: 'à partir de 16h' }] },
        { entities: [{ entityType: 'LISTING', entityId: SMALL_ID }], texts: [{ message: 'à partir de 18h' }] },
      ]),
    ]).listings;
    expect(listing.check_in_time).toBeUndefined();
  });

  it('ne lit rien d\'autre que l\'heure d\'arrivée', () => {
    const [listing] = parseExportDocuments([
      listingsDoc([rawListing()]),
      quickRepliesDoc([{
        entities: [{ entityType: 'LISTING', entityId: SMALL_ID }],
        texts: [{ message: 'Le code de la boîte à clés est 1009. Le wifi est LIVEBOX-4A2B.' }],
      }]),
    ]).listings;
    // Un code et un nom de réseau lus dans un message peuvent être périmés,
    // ou avoir été donnés à un seul voyageur. Ils ne deviennent pas des
    // caractéristiques.
    expect(listing.access_code).toBeUndefined();
    expect(listing.wifi_name).toBeUndefined();
    expect(JSON.stringify(listing)).not.toContain('1009');
  });
});

// ────────────────────────────────────────────────────────────────────────────
describe('traçabilité et arbitrage des conflits', () => {
  const permitsAddress = {
    name: 'listing_permits.json',
    data: [{ listingRegistrations: [{
      listingUrl: `https://www.airbnb.com/rooms/${SMALL_ID}`,
      registrations: [{ registrationSubmissions: [{ data: { listing_address: 'Adresse déclarée différente' } }] }],
    }] }],
  };

  it('note le fichier d\'origine de chaque champ', () => {
    const [listing] = parseExportDocuments([listingsDoc([rawListing()])]).listings;
    expect(listing.import_sources.name).toBe('listings.json');
    expect(listing.import_sources.max_guests).toBe('listings.json');
    expect(listing.import_sources.has_wifi).toBe('listings.json');
  });

  it('la source la plus autoritative garde la main, et le désaccord est noté', () => {
    const { listings, conflicts } = parseExportDocuments([
      listingsDoc([rawListing()]), permitsAddress,
    ]);
    expect(listings[0].address).toBe('12 Rue des Ardillères, 33290 Parempuyre, France');
    expect(listings[0].import_sources.address).toBe('listings.json');
    expect(conflicts).toContainEqual({
      listing_id: SMALL_ID,
      field: 'address',
      kept_from: 'listings.json',
      ignored_from: 'listing_permits.json',
    });
  });

  it('ne signale aucun conflit quand les deux sources concordent', () => {
    const same = {
      name: 'listing_permits.json',
      data: [{ listingRegistrations: [{
        listingUrl: `https://www.airbnb.com/rooms/${SMALL_ID}`,
        registrations: [{ registrationSubmissions: [{
          data: { listing_address: '12 Rue des Ardillères, 33290 Parempuyre, France' },
        }] }],
      }] }],
    };
    const { conflicts } = parseExportDocuments([listingsDoc([rawListing()]), same]);
    expect(conflicts).toEqual([]);
  });

  it('une source secondaire comble un vide sans jamais écraser', () => {
    const { listings } = parseExportDocuments([
      listingsDoc([rawListing({ formattedAddress: '', street: '', zipcode: '', city: '', country: '' })]),
      permitsAddress,
    ]);
    expect(listings[0].address).toBe('Adresse déclarée différente');
    expect(listings[0].import_sources.address).toBe('listing_permits.json');
  });
});

// ────────────────────────────────────────────────────────────────────────────
describe('rien n\'est inventé', () => {
  it('ne remplace pas une valeur absente par un zéro', () => {
    const [listing] = parseExportDocuments([listingsDoc([
      rawListing({ bedrooms: null, beds: null, personCapacity: null, bathrooms: null }),
    ])]).listings;
    expect(listing.bedrooms).toBeUndefined();
    expect(listing.beds).toBeUndefined();
    expect(listing.max_guests).toBeUndefined();
    expect(listing.bathrooms).toBeUndefined();
    expect(listing.found.capacity).toBe(false);
  });

  it('ne coche aucun équipement quand la liste est absente', () => {
    const [listing] = parseExportDocuments([listingsDoc([
      rawListing({ amenities: null }),
    ])]).listings;
    expect(Object.keys(listing).filter((k) => k.startsWith('has_'))).toEqual([]);
    expect(listing.found.amenities).toBe(false);
  });

  it('n\'écrit pas d\'instructions que l\'hôte n\'a pas écrites', () => {
    const [listing] = parseExportDocuments([listingsDoc([
      rawListing({ amenities: ['cleaning_before_checkout', 'luggage_dropoff_allowed'] }),
    ])]).listings;
    // Ces deux codes disent qu'une chose est possible, pas comment ni à quelle
    // condition. Les phrases correspondantes auraient été écrites par nous.
    expect(listing.checkout_instructions).toBeUndefined();
    expect(listing.luggage_storage).toBeUndefined();
  });

  it('conserve la valeur exacte des demi-salles de bain', () => {
    const [listing] = parseExportDocuments([listingsDoc([rawListing({ bathrooms: 1.5 })])]).listings;
    // La colonne est entière, mais ce n'est pas elle que Michel cite.
    expect(listing.bathrooms).toBe(2);
    expect(listing.bathrooms_exact).toBe(1.5);
  });

  it('reprend le règlement écrit par l\'hôte plutôt que de le reformuler', () => {
    const [listing] = parseExportDocuments([listingsDoc([rawListing({
      listingDescriptions: [{ name: 'Test', houseRules: 'Pas de musique après 22 h.' }],
    })])]).listings;
    expect(listing.house_rules).toContain('Pas de musique après 22 h.');
  });

  it('ne traduit pas un type de logement absent du menu de la fiche', () => {
    const [listing] = parseExportDocuments([listingsDoc([
      rawListing({ propertyType: 'Yourte mongole' }),
    ])]).listings;
    expect(listing.property_type).toBeUndefined();
  });
});
